### PR TITLE
Have the pure-python implementation avoid wrapping __parent__.

### PR DESCRIPTION
**Pull request by jamadden**
Fix issue #3. Test this.

### CODE REVIEW

**Comment by tseaver** [comment]
The new test passes for me under `tox -e py27-pure` even without the change to `ExtensionClass.__init__.py`.  We need a test that fails without the fix.

**Comment by jamadden** [comment]
Fascinating. I also do not see a failure with either `tox -e pypy` or `tox -e py27-pure` (incidentally, I had to add `include *.rst` to `MANIFEST.in` to get tox to package correctly, since the .rst files are read in setup.py).

However, using `bin/test` in a buildout setup with PyPy (what I tested with initially), I get the expected failure:

```
$ bin/test
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.


Failure in test test__parent__does_not_get_wrapped (ExtensionClass.tests)
Failed doctest test for ExtensionClass.tests.test__parent__does_not_get_wrapped
  File "//ExtensionClass/src/ExtensionClass/tests.py", line 847, in test__parent__does_not_get_wrapped

----------------------------------------------------------------------
File "//ExtensionClass/src/ExtensionClass/tests.py", line 870, in ExtensionClass.tests.test__parent__does_not_get_wrapped
Failed example:
    x.__parent__
Expected:
    b
Got:
    'wrapped'

  Ran 25 tests with 1 failures, 0 errors and 0 skipped in 0.044 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
```

Checking to see why that might be...

**Comment by jamadden** [comment]
It almost looks like `nose` isn't even running the doctest examples. Introducing blatant syntax errors in them still doesn't produce test failures.

**Comment by tseaver** [comment]
Looks like it needs `--where=src`.

**Comment by jamadden** [comment]
Thanks, that did it. I can now reproduce the failures under tox as well as `bin/test`.

**Comment by jamadden** [comment]
FWIW, I think the .travis.yml has the same issue of not actually running the doctest examples.

**Comment by tseaver** [comment]
I have added a `setup.cfg` which gets the doctests run (should workf for both tox and Travis).  Can you please merge with master (or rebase) and re-push?

**Comment by jamadden** [comment]
Thanks, that seemed to do it.

**Comment by tseaver** [comment]
Fix released with https://pypi.python.org/pypi/ExtensionClass/4.1.1

**Pull request merged**
