### PR TITLE
Add support for Python 3.10.

### PR DESCRIPTION
**Pull request by icemac**
This PR is built on https://github.com/zopefoundation/meta/pull/115 to improve it for the type `c-code`.

### CODE REVIEW

**Comment by icemac** [comment]
The docker configurations used to build the manylinux wheels do not yet contain a Python 3.10 (or it is not named `/opt/python/*cp310*/bin/*`).

**Comment by icemac** [comment]
I looked into the docker container: We are just using too old versions for `manylinux2010*`.

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
Breaks on AppVeyor as Python 3.10 cannot be installed there as there is no Python 3.10 Windows exe at https://www.python.org/ftp/python, yet.

**Comment by icemac** [comment]
Ideas to solve the problem:

* Omit Python 3.10 for windows now.
* Switch to GHA for Windows – maybe `cibuildwheels` could make the build process easier

**Comment by icemac** [comment]
I decided for disabling Python 3.10 on AppVeyor for now.

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
