### PR TITLE
Try out cibuildwheel.

### PR DESCRIPTION
**Pull request by icemac**
Open issues:

- [x] Tests do not run on windows — I was unable to find a way to convey zope.testrunner to use my `--test-path` pointing to the site-packages.
- [ ] Report coverage to coveralls.io
- [x] Run tests for Python < 3.6
- [x] Run tests for PyPy and PyPy3
- [ ] Build and test on Python 3.11 but never upload a wheel for a non-final Python version

As we usually use [meta/config](https://github.com/zopefoundation/meta/tree/master/config) to configure all our projects the same way, I have to integrate the changes made here over there. But this could be done after this PR is merged.

### CODE REVIEW

**Comment by fgregg** [comment]
hi @icemac , is the todo list still current? looks like you did some of these items?

**Comment by fgregg** [comment]
can't use cibuildwheel with pypy since cibuildwheel only wants to build binary extensions, and setup.py is set up to build a pure python package if we are using pypy

https://github.com/zopefoundation/ExtensionClass/blob/0d89bccaf69b640c4fd2157f9b7dda79a23ce82c/setup.py#L30-L31

**Comment by fgregg** [comment]
cibuildwheel won't work for running test on cpython < 3.6 or pypi. should we write a separate path for those in the github actions?

**Comment by d-maurer** [comment]
Forest Gregg wrote at 2022-2-27 08:41 -0800:
>can't use cibuildwheel with pypy since cibuildwheel only wants to build binary extensions, and setup.py is set up to build a pure python package if we are using pypy

Why do you want to build a "pypy" wheel?
Apparently, "pypy" cannot use C extensions (at least I saw
something like `use_C = not PYPY and not PURE_PYTHON` in a different package).
Should this be true, "pypy" could simple use the source distribution.

**Comment by fgregg** [comment]
@icemac here's an example of coverage integration with cibuildwheel: https://github.com/pyutils/line_profiler/pull/76/files

**Comment by icemac** [comment]
> hi @icemac , is the todo list still current? looks like you did some of these items?

The items on the todo list are still to do, e. g. on windows still 0 tests are running.

**Comment by dataflake** [comment]
@icemac This can be close, right?

**Comment by icemac** [comment]
The experiments with cibuildwheel where no so successful. So let's close it as we currently have a working solution.

**Pull request closed without merging**
